### ISSUE TITLE
Getting Started Tutorial: 100 or 1000: Comment does not match following line of code

### ISSUE THREAD

**Issue by kasettli** [hammal/cbadc#64]
https://github.com/hammal/cbadc/blob/3721af54386c71d95f963c5afa909c749e03020a/docs/code_examples/a_getting_started/plot_b_simulate_a_control_bounded_adc.py#L216

The comment mentions three orders of magnitude (1000) while line 217 shows only a factor of 100

**Comment by hammal** [comment]
Thanks will fix in next PR.

**Comment by kasettli** [comment]
Possibly the next two lines also don‘t match. To be more precise:
The comment should say „simulate for 150 control cycles“
